---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
  labels:
    app.kubernetes.io/managed-by: flux
    platform.mlops.io/cluster-tier: dev
data:
  environment: dev
  gcp_project: mlops-platform-dev
  gcp_region: us-central1
  teams_webhook_url: https://outlook.office.com/webhook/dev-placeholder
