{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ml-gateway.fullname" . }}
  labels:
    {{- include "ml-gateway.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.serviceMonitor.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ml-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
